
export const cardData = [
    {
        image: 'blog-type-1.png',
        blogType: 'Sales & Marketing',
        blogDate: 'Nov 3, 2023',
        heading: 'User Experience: HR Recruitment Software Adoption',
        content: 'Leading AI tools like Salesforce Einstein, Marketo, and HubSpot employ high-performing algorithms to enhance the performance of sales conversions. They offer predictive analytics, personalized recommendations to deal with every client, and automated workflows for efficient usage of time, empowering businesses to have hands-on leads effectively and close more deals.',
    },
    {
        image: 'blog-type-2.png',
        blogType: 'Sales & Marketing',
        blogDate: 'Nov 3, 2023',
        heading: 'User Experience: HR Recruitment Software Adoption',
        content: 'Leading AI tools like Salesforce Einstein, Marketo, and HubSpot employ high-performing algorithms to enhance the performance of sales conversions. They offer predictive analytics, personalized recommendations to deal with every client, and automated workflows for efficient usage of time, empowering businesses to have hands-on leads effectively and close more deals.',
    },
    {
        image: 'blog-type-3.png',
        blogType: 'Sales & Marketing',
        blogDate: 'Nov 3, 2023',
        heading: 'groko User Experience: HR Recruitment Software Adoption',
        content: 'Leading AI tools like Salesforce Einstein, Marketo, and HubSpot employ high-performing algorithms to enhance the performance of sales conversions. They offer predictive analytics, personalized recommendations to deal with every client, and automated workflows for efficient usage of time, empowering businesses to have hands-on leads effectively and close more deals.',
    },
    {
        image: 'blog-type-4.png',
        blogType: 'Sales & Marketing',
        blogDate: 'Nov 3, 2023',
        heading: 'User Experience: HR Recruitment Software Adoption',
        content: 'Leading AI tools like Salesforce Einstein, Marketo, and HubSpot employ high-performing algorithms to enhance the performance of sales conversions. They offer predictive analytics, personalized recommendations to deal with every client, and automated workflows for efficient usage of time, empowering businesses to have hands-on leads effectively and close more deals.',
    },
    {
        image: 'blog-type-1.png',
        blogType: 'Sales & Marketing',
        blogDate: 'Nov 3, 2023',
        heading: 'User Experience: HR Recruitment Software Adoption',
        content: 'Leading AI tools like Salesforce Einstein, Marketo, and HubSpot employ high-performing algorithms to enhance the performance of sales conversions. They offer predictive analytics, personalized recommendations to deal with every client, and automated workflows for efficient usage of time, empowering businesses to have hands-on leads effectively and close more deals.',
    },
    {
        image: 'blog-type-2.png',
        blogType: 'Sales & Marketing',
        blogDate: 'Nov 3, 2023',
        heading: 'User Experience: HR Recruitment Software Adoption',
        content: 'Leading AI tools like Salesforce Einstein, Marketo, and HubSpot employ high-performing algorithms to enhance the performance of sales conversions. They offer predictive analytics, personalized recommendations to deal with every client, and automated workflows for efficient usage of time, empowering businesses to have hands-on leads effectively and close more deals.',
    },
    {
        image: 'blog-type-1.png',
        blogType: 'Sales & Marketing',
        blogDate: 'Nov 3, 2023',
        heading: 'User Experience: HR Recruitment Software Adoption',
        content: 'Leading AI tools like Salesforce Einstein, Marketo, and HubSpot employ high-performing algorithms to enhance the performance of sales conversions. They offer predictive analytics, personalized recommendations to deal with every client, and automated workflows for efficient usage of time, empowering businesses to have hands-on leads effectively and close more deals.',
    },
    {
        image: 'blog-type-2.png',
        blogType: 'Sales & Marketing',
        blogDate: 'Nov 3, 2023',
        heading: 'User Experience: HR Recruitment Software Adoption',
        content: 'Leading AI tools like Salesforce Einstein, Marketo, and HubSpot employ high-performing algorithms to enhance the performance of sales conversions. They offer predictive analytics, personalized recommendations to deal with every client, and automated workflows for efficient usage of time, empowering businesses to have hands-on leads effectively and close more deals.',
    },
    {
        image: 'blog-type-3.png',
        blogType: 'Sales & Marketing',
        blogDate: 'Nov 3, 2023',
        heading: 'User Experience: HR Recruitment Software Adoption',
        content: 'Leading AI tools like Salesforce Einstein, Marketo, and HubSpot employ high-performing algorithms to enhance the performance of sales conversions. They offer predictive analytics, personalized recommendations to deal with every client, and automated workflows for efficient usage of time, empowering businesses to have hands-on leads effectively and close more deals.',
    },
    {
        image: 'blog-type-4.png',
        blogType: 'Sales & Marketing',
        blogDate: 'Nov 3, 2023',
        heading: 'User Experience: HR Recruitment Software Adoption',
        content: 'Leading AI tools like Salesforce Einstein, Marketo, and HubSpot employ high-performing algorithms to enhance the performance of sales conversions. They offer predictive analytics, personalized recommendations to deal with every client, and automated workflows for efficient usage of time, empowering businesses to have hands-on leads effectively and close more deals.',
    },
    {
        image: 'blog-type-1.png',
        blogType: 'Sales & Marketing',
        blogDate: 'Nov 3, 2023',
        heading: 'User Experience: HR Recruitment Software Adoption',
        content: 'Leading AI tools like Salesforce Einstein, Marketo, and HubSpot employ high-performing algorithms to enhance the performance of sales conversions. They offer predictive analytics, personalized recommendations to deal with every client, and automated workflows for efficient usage of time, empowering businesses to have hands-on leads effectively and close more deals.',
    },
    {
        image: 'blog-type-2.png',
        blogType: 'Sales & Marketing',
        blogDate: 'Nov 3, 2023',
        heading: ' test search User Experience: HR Recruitment Software Adoption',
        content: 'Leading AI tools like Salesforce Einstein, Marketo, and HubSpot employ high-performing algorithms to enhance the performance of sales conversions. They offer predictive analytics, personalized recommendations to deal with every client, and automated workflows for efficient usage of time, empowering businesses to have hands-on leads effectively and close more deals.',
    },
];
