version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.13.1
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  files:
    - '.next/**/*'

cache:
  paths:
    - node_modules/**/*

