version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing Node.js 14.x..."
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
      - export NVM_DIR="$HOME/.nvm"
      - source "$NVM_DIR/nvm.sh"
      - nvm install 14
      - node -v
      - npm -v
      - npm install -g yarn

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - yarn install

  build:
    commands:
      - echo "Building Next.js application..."
      - yarn build

  post_build:
    commands:
      - echo "Running tests..."
      - yarn test

artifacts:
  files:
    - '**/*'
    - '!node_modules/**/*'
