version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building Next.js project..."
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: '.next'
