version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js 18.17.0..."
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
      - export NVM_DIR="$HOME/.nvm"
      - . "$NVM_DIR/nvm.sh" # This loads nvm
      - nvm install 18.17.0
      - nvm use 18.17.0
  build:
    commands:
      - echo "Build phase"
      # Your build commands here
